apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api-deployment
  namespace: buy-better

spec:
  replicas: 1

  template:
    spec:
      containers:
        - name: core-api
          imagePullPolicy: Never
          env:
            - name: WEB_SERVICE_ENV
              value: "cluster-dev"
            - name: DB_DSN # dev local db is not sensitive
              value: "postgresql://postgres:admin1234@host.minikube.internal:5433/buy-better-core?sslmode=disable"
            - name: GOOGLE_CALLBACK
              value: "http://127.0.0.1:3030/v1/auth/google/callback"
            - name: TOKEN_ENCODED
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: TOKEN_ENCODED
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: GOOGLE_CLIENT_SECRET
          resources:
            requests:
              cpu: "500m"
            limits:
              cpu: "500m"

          livenessProbe:
            httpGet:
              path: /v1/liveness
              port: 3030
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 4

          readinessProbe:
            httpGet:
              path: /v1/readiness
              port: 3030
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 4


