apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/
patches:
  - path: ./dev-service-patch.yaml
  - path: ./dev-deployment-patch.yaml
images:
  - name: core-api-image
    newName: opplieam/bb-core-api
    newTag: cluster-dev