services:
  pg-core-dev-db:
    image: postgres:16.2-alpine3.19
    container_name: pg-core-dev-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    env_file:
      - ./.postgres.env
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "4317:4317" # accept OpenTelemetry Protocol (OTLP) over gRPC
      - "14268:14268" # accept jaeger.thrift directly from clients