# DONT FORGET TO UPDATE IMAGE TAG BY --set image.tag=xxx

# Namespace
namespace: buy-better

# Service
service:
  type: ClusterIP
  port: 3030

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90
#  targetMemoryUtilizationPercentage: 90

replicaCount: 1

# Container Image
image:
  repository: opplieam/bb-core-api
  pullPolicy: Always
  tag: ""
imagePullSecrets: []

# Environment
env:
  webService: "prod"
  prodServiceAddr: "bb-product-server.buy-better.svc.cluster.local:3031"
  googleCallback: "http://127.0.0.1:3030/v1/auth/google/callback"
  jaegerEndpoint: "http://host.minikube.internal:14268/api/traces"


# liveness Probe
livenessProbe:
  httpGet:
    path: /v1/liveness
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 4

# Readiness Probe
readinessProbe:
  httpGet:
    path: /v1/readiness
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 4


ingress:
  enabled: true
  className: nginx
  host: "bb-core.thanyasit.dev"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  paths:
    - path: /
      pathType: Prefix
      servicePort: 3030

certManager:
  enabled: true





