apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bb-core-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bb-core-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bb-core-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "bb-core-api.fullname" . }}
      labels: {{- include "bb-core-api.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: KUBERNETES_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: WEB_SERVICE_ENV
              value: {{ .Values.env.webService }}
            - name: PRODUCT_SERVICE_ADDR
              value: {{ .Values.env.prodServiceAddr }}
            - name: GOOGLE_CALLBACK
              value: {{ .Values.env.googleCallback }}
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: {{ .Values.env.jaegerEndpoint }}
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: DB_DSN
            - name: TOKEN_ENCODED
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: TOKEN_ENCODED
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: core-api-secret
                  key: SESSION_SECRET
