apiVersion: v1
kind: Service
metadata:
  name: {{ include "bb-core-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bb-core-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "bb-core-api.selectorLabels" . | nindent 4 }}
