apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api-deployment
  namespace: buy-better

spec:
  selector:
    matchLabels:
      app: core-api

  template:
    metadata:
      labels:
        app: core-api
    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: core-api
          image: core-api-image
          ports:
            - name: core-api-port
              containerPort: 3030

          livenessProbe:
            httpGet:
              path: /v1/liveness
              port: 3030
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 4

          readinessProbe:
            httpGet:
              path: /v1/readiness
              port: 3030
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 4

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: KUBERNETES_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

