name: CI
on:
  workflow_dispatch:
jobs:
#  test:
#    name: Unit test
#    runs-on: ubuntu-latest
#    environment: Github Action
#    env:
#      TOKEN_ENCODED: ${{ secrets.TOKEN_ENCODED }}
#
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v4
#
#      - name: Setup Go environment
#        uses: actions/setup-go@v5.0.2
#        with:
#          go-version: '1.22.2'
#
#      - name: Cache Go modules
#        uses: actions/cache@v3
#        with:
#          path: ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-
#
#      - name: Get dependencies
#        run: go mod download
#
#      - name: Run unit test
#        run: make test-unit

  build_images_and_push:
    name: Build docker image and push
#    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: make docker-build-prod

      - name: Push to Docker hub
        run: make docker-push

      - name: echo Image name
        run: echo "0.0.1-$(git rev-parse --short HEAD)"

